services:
  vllm:
    # image: ${VLLM_IMAGE}
    build:
      context: ${VLLM_BUILD_CONTEXT}
      dockerfile: ${VLLM_DOCKERFILE}
      shm_size: ${SHM_SIZE}
      args:
        BUILDKIT_CONTEXT_KEEP_GIT_DIR: "1"
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    ipc: host
    shm_size: ${SHM_SIZE}
    volumes:
      - ${MODEL_MOUNT_PATH}:/llm/models/
    ports:
      - "${HOST_PORT}:8000"
    environment:
      - VLLM_WORKER_MULTIPROC_METHOD=${VLLM_WORKER_MULTIPROC_METHOD}
      - ZE_AFFINITY_MASK=${ZE_AFFINITY_MASK}
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=${HF_HOME}

    entrypoint: /bin/bash
    command: >
      -c "source /opt/intel/oneapi/setvars.sh --force &&
      python3 -m vllm.entrypoints.openai.api_server
      --model ${MODEL_NAME}
      --tensor-parallel-size ${TP_SIZE}
      --kv-cache-dtype ${KV_CACHE_DTYPE}
      --max-model-len ${MAX_MODEL_LEN}
      ${QUANT_ARG}
      ${EXTRA_ARGS}"
